name: gitrat
description: A Dart Console App to get my GitHub Traitors.
version: 0.1.0
author: piedcipher

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: any

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
